"""Kandidaten für „Serien & Disney“: (Serie/Film, Startjahr, Suchanfrage, Interpret-Hinweis).

Jahr = Start der Serie bzw. Erscheinungsjahr des Films (Wunsch des Nutzers).
Kinderserien und Anime in der deutschen Fassung, Erwachsenen-Serien und Disney-Filmsongs im Original.
"""
ENTRIES = [
 # Kult-Serien
 ('Friends', 1994, "The Rembrandts I'll Be There for You", 'Rembrandts'),
 ('Der Prinz von Bel-Air', 1990, 'Fresh Prince of Bel-Air theme DJ Jazzy Jeff', 'Jazzy Jeff'),
 ('Die Simpsons', 1989, 'Danny Elfman The Simpsons Theme', 'Elfman'),
 ('Malcolm mittendrin', 2000, 'They Might Be Giants Boss of Me', 'They Might Be Giants'),
 ('Scrubs', 2001, 'Lazlo Bane Superman', 'Lazlo Bane'),
 ('How I Met Your Mother', 2005, 'The Solids Hey Beautiful', 'Solids'),
 ('The Big Bang Theory', 2007, 'Barenaked Ladies Big Bang Theory Theme', 'Barenaked'),
 ('Baywatch', 1989, "Jimi Jamison I'm Always Here", 'Jamison'),
 ('Eine schrecklich nette Familie', 1987, 'Frank Sinatra Love and Marriage', 'Sinatra'),
 ('Charmed', 1998, 'Love Spit Love How Soon Is Now', 'Love Spit Love'),
 ("Dawson's Creek", 1998, "Paula Cole I Don't Want to Wait", 'Paula Cole'),
 ('O.C., California', 2003, 'Phantom Planet California', 'Phantom Planet'),
 ('One Tree Hill', 2003, "Gavin DeGraw I Don't Want to Be", 'DeGraw'),
 ('Gilmore Girls', 2000, 'Carole King Where You Lead', 'Carole King'),
 ('Full House', 1987, 'Jesse Frederick Everywhere You Look', 'Frederick'),
 ('Die Nanny', 1993, 'The Nanny Named Fran', 'Callaway'),
 ('The Office', 2005, 'The Office Theme Scrantones', 'Scrantones'),
 ('Die Sopranos', 1999, 'Alabama 3 Woke Up This Morning', 'Alabama 3'),
 ('True Blood', 2008, 'Jace Everett Bad Things', 'Everett'),
 ('Sons of Anarchy', 2008, 'Curtis Stigers This Life', 'Stigers'),
 ('Pretty Little Liars', 2010, 'The Pierces Secret', 'Pierces'),
 ('Peaky Blinders', 2013, 'Nick Cave Red Right Hand', 'Nick Cave'),
 ('Mad Men', 2007, 'RJD2 A Beautiful Mine', 'RJD2'),
 ('Vikings', 2013, 'Fever Ray If I Had a Heart', 'Fever Ray'),
 ('Big Little Lies', 2017, 'Michael Kiwanuka Cold Little Heart', 'Kiwanuka'),
 ('Haus des Geldes', 2017, 'Bella Ciao Manu Pilas', 'Pilas'),
 ('Narcos', 2015, 'Rodrigo Amarante Tuyo', 'Amarante'),
 ('Brooklyn Nine-Nine', 2013, 'Brooklyn Nine-Nine theme Dan Marocco', 'Marocco'),
 ('Desperate Housewives', 2004, 'Danny Elfman Desperate Housewives', 'Elfman'),
 ('Akte X', 1993, 'Mark Snow The X-Files theme', 'Mark Snow'),
 ('Twin Peaks', 1990, 'Angelo Badalamenti Twin Peaks Theme', 'Badalamenti'),
 ('Miami Vice', 1984, 'Jan Hammer Miami Vice Theme', 'Jan Hammer'),
 ('Das A-Team', 1983, 'A-Team Theme Mike Post', 'Mike Post'),
 ('MacGyver', 1985, 'MacGyver Theme Randy Edelman', 'Edelman'),
 ('Knight Rider', 1982, 'Knight Rider Theme Stu Phillips', 'Phillips'),
 ('Ein Colt für alle Fälle', 1981, 'Lee Majors Unknown Stuntman', 'Majors'),
 ('Game of Thrones', 2011, 'Ramin Djawadi Main Title Game of Thrones', 'Djawadi'),
 ('House of the Dragon', 2022, 'Ramin Djawadi House of the Dragon Main Theme', 'Djawadi'),
 ('Westworld', 2016, 'Ramin Djawadi Westworld Main Title', 'Djawadi'),
 ('Prison Break', 2005, 'Ramin Djawadi Prison Break Main Title', 'Djawadi'),
 ('Stranger Things', 2016, 'Kyle Dixon Michael Stein Stranger Things', 'Dixon'),
 ('Squid Game', 2021, 'Jung Jae Il Way Back Then', 'Jung'),
 ('The Walking Dead', 2010, 'Bear McCreary The Walking Dead Main Title', 'McCreary'),
 ('The Mandalorian', 2019, 'Ludwig Goransson The Mandalorian', 'Göransson'),
 ('Sherlock', 2010, 'David Arnold Michael Price Sherlock Theme', 'Arnold'),
 ('Succession', 2018, 'Nicholas Britell Succession Main Title Theme', 'Britell'),
 ('The Last of Us', 2023, 'Gustavo Santaolalla The Last of Us', 'Santaolalla'),
 ('Breaking Bad', 2008, 'Dave Porter Breaking Bad Main Title Theme', 'Porter'),
 ('Wednesday', 2022, 'Danny Elfman Wednesday Main Titles', 'Elfman'),
 ('Dark', 2017, 'Apparat Goodbye', 'Apparat'),
 ('Babylon Berlin', 2017, 'Severija Zu Asche zu Staub', 'Severija'),
 ('Bridgerton', 2020, 'Bridgerton Kris Bowers', 'Bowers'),
 ('Doctor Who', 1963, 'Doctor Who Theme Murray Gold', 'Gold'),
 # Deutsche Klassiker
 ('Tatort', 1970, 'Klaus Doldinger Tatort', 'Doldinger'),
 ('Lindenstraße', 1985, 'Lindenstraße Titelmusik Jürgen Knieper', 'Knieper'),
 ('Gute Zeiten, schlechte Zeiten', 1992, 'Gute Zeiten schlechte Zeiten Titelsong', ''),
 ('Alarm für Cobra 11', 1996, 'Alarm für Cobra 11 Titelmusik', ''),
 ('Das Traumschiff', 1981, 'Das Traumschiff Titelmelodie James Last', 'Last'),
 ('Die Sendung mit der Maus', 1971, 'Die Sendung mit der Maus Titelmusik', ''),
 ('Löwenzahn', 1981, 'Löwenzahn Titelmusik', ''),
 ('Unser Sandmännchen', 1959, 'Sandmann lieber Sandmann', ''),
 ('Meister Eder und sein Pumuckl', 1982, 'Pumuckl Titellied Hurra', ''),
 ('Die Biene Maja', 1975, 'Karel Gott Biene Maja', 'Karel Gott'),
 ('Wickie und die starken Männer', 1974, 'Wickie Titelsong Hey hey Wickie', ''),
 ('Heidi', 1974, 'Gitti und Erika Heidi', 'Gitti'),
 ('Pippi Langstrumpf', 1969, 'Hey Pippi Langstrumpf', ''),
 ('Benjamin Blümchen', 1977, 'Benjamin Blümchen Titellied Törööö', ''),
 ('Bibi Blocksberg', 1980, 'Bibi Blocksberg Lied', ''),
 ('Bibi & Tina', 1991, 'Bibi und Tina Lied', ''),
 ('Tabaluga', 1997, 'Peter Maffay Tabaluga', 'Maffay'),
 ('Sesamstraße', 1973, 'Sesamstraße Der die das', ''),
 ('Die Schlümpfe', 1981, 'Die Schlümpfe Titellied', ''),
 ('Alfred J. Kwak', 1989, 'Alfred J. Kwak Titellied Hermann van Veen', 'Veen'),
 ('Die Gummibärenbande', 1985, 'Gummibärenbande Titellied deutsch', ''),
 ('DuckTales', 1987, 'DuckTales Titellied deutsch', ''),
 ('Chip und Chap – Die Ritter des Rechts', 1989, 'Chip und Chap Ritter des Rechts Titellied', ''),
 ('Darkwing Duck', 1991, 'Darkwing Duck Titellied deutsch', ''),
 ("Käpt'n Balu und seine tollkühne Crew", 1990, 'Käpt n Balu Titellied', ''),
 # Anime & Zeichentrick (deutsch)
 ('Pokémon', 1997, 'Pokémon Titelsong deutsch Schnapp sie dir alle', ''),
 ('Digimon', 1999, 'Digimon Titelsong deutsch', ''),
 ('Dragon Ball Z', 1989, 'Dragonball Z Titelsong deutsch', ''),
 ('Sailor Moon', 1992, 'Sailor Moon Titelsong deutsch', ''),
 ('Yu-Gi-Oh!', 2000, 'Yu-Gi-Oh Titelsong deutsch', ''),
 ('Detektiv Conan', 1996, 'Detektiv Conan Titelsong deutsch', ''),
 ('One Piece', 1999, 'One Piece Titelsong deutsch', ''),
 ('Naruto', 2002, 'Naruto Titelsong deutsch', ''),
 ('Captain Tsubasa', 1983, 'Die tollen Fußballstars Titelsong', ''),
 ('SpongeBob Schwammkopf', 1999, 'SpongeBob Schwammkopf Titellied', ''),
 ('Teenage Mutant Ninja Turtles', 1987, 'Teenage Mutant Hero Turtles Titellied', ''),
 ('Totally Spies', 2001, 'Totally Spies Titelsong', ''),
 ('Ben 10', 2005, 'Ben 10 Theme', ''),
 ('Kim Possible', 2002, 'Christina Milian Call Me Beep Me', 'Milian'),
 ('Phineas und Ferb', 2007, 'Phineas und Ferb Titelsong', ''),
 ('Gravity Falls', 2012, 'Gravity Falls Main Title Theme', ''),
 ('Miraculous', 2015, 'Miraculous Titelsong deutsch', ''),
 ('Paw Patrol', 2013, 'Paw Patrol Titelsong deutsch', ''),
 ('Peppa Wutz', 2004, 'Peppa Wutz Titelmusik', ''),
 ('Bob der Baumeister', 1998, 'Bob der Baumeister Titellied', ''),
 ('Teletubbies', 1997, 'Teletubbies Titellied', ''),
 ('Bluey', 2018, 'Bluey Theme Tune', ''),
 ('H2O – Plötzlich Meerjungfrau', 2006, 'Kate Alexa No Ordinary Girl', 'Alexa'),
 # Disney Channel & Nickelodeon (Original)
 ('Hannah Montana', 2006, 'Hannah Montana The Best of Both Worlds', 'Hannah Montana'),
 ('iCarly', 2007, 'Miranda Cosgrove Leave It All to Me', 'Cosgrove'),
 ('Victorious', 2010, 'Victoria Justice Make It Shine', 'Victoria Justice'),
 ('Big Time Rush', 2009, 'Big Time Rush Big Time Rush', 'Big Time Rush'),
 ('Raven blickt durch', 2003, "That's So Raven theme", 'Raven'),
 ('Zoey 101', 2005, 'Jamie Lynn Spears Follow Me', 'Spears'),
 ('Drake & Josh', 2004, 'Drake Bell Found a Way', 'Drake Bell'),
 ('Die Zauberer vom Waverly Place', 2007, 'Selena Gomez Everything Is Not What It Seems', 'Selena'),
 ('Austin & Ally', 2011, 'Ross Lynch Can You Feel It', 'Lynch'),
 # Disney- & Animationsfilme (Original)
 ('Der König der Löwen', 1994, 'Hakuna Matata Lion King', ''),
 ('Der König der Löwen', 1994, 'Circle of Life Carmen Twillie', 'Twillie'),
 ('Der König der Löwen', 1994, "Can You Feel the Love Tonight Elton John", 'Elton'),
 ('Arielle, die Meerjungfrau', 1989, 'Under the Sea Samuel E. Wright', 'Wright'),
 ('Arielle, die Meerjungfrau', 1989, 'Part of Your World Jodi Benson', 'Benson'),
 ('Aladdin', 1992, 'A Whole New World Brad Kane Lea Salonga', 'Kane'),
 ('Aladdin', 1992, 'Friend Like Me Robin Williams', 'Williams'),
 ('Die Schöne und das Biest', 1991, 'Beauty and the Beast Angela Lansbury', 'Lansbury'),
 ('Das Dschungelbuch', 1967, 'The Bare Necessities Phil Harris', 'Harris'),
 ('Pocahontas', 1995, 'Colors of the Wind Judy Kuhn', 'Kuhn'),
 ('Mulan', 1998, "I'll Make a Man Out of You Donny Osmond", 'Osmond'),
 ('Hercules', 1997, "I Won't Say I'm in Love Susan Egan", 'Egan'),
 ('Toy Story', 1995, "You've Got a Friend in Me Randy Newman", 'Newman'),
 ('Tarzan', 1999, "Phil Collins You'll Be in My Heart", 'Collins'),
 ('Die Eiskönigin', 2013, 'Let It Go Idina Menzel', 'Menzel'),
 ('Die Eiskönigin', 2013, 'Do You Want to Build a Snowman Kristen Bell', 'Bell'),
 ('Die Eiskönigin 2', 2019, 'Into the Unknown Idina Menzel', 'Menzel'),
 ('Vaiana', 2016, "How Far I'll Go Auli'i Cravalho", 'Cravalho'),
 ('Vaiana', 2016, "You're Welcome Dwayne Johnson", 'Johnson'),
 ('Encanto', 2021, "We Don't Talk About Bruno", 'Encanto'),
 ('Rapunzel – Neu verföhnt', 2010, 'I See the Light Mandy Moore', 'Moore'),
 ('Coco', 2017, 'Remember Me Coco', ''),
 ('Zoomania', 2016, 'Shakira Try Everything', 'Shakira'),
 ('Cars', 2006, 'Rascal Flatts Life Is a Highway', 'Rascal Flatts'),
 ('Fluch der Karibik', 2003, "Klaus Badelt He's a Pirate", 'Badelt'),
 ('Shrek', 2001, 'Smash Mouth All Star', 'Smash Mouth'),
 ('Shrek', 2001, "Smash Mouth I'm a Believer", 'Smash Mouth'),
 ('High School Musical', 2006, 'Breaking Free High School Musical', 'Troy'),
 ('High School Musical', 2006, "We're All in This Together High School Musical", ''),
 ('High School Musical 2', 2007, 'What Time Is It High School Musical 2', ''),
 ('Camp Rock', 2008, 'This Is Me Demi Lovato Joe Jonas', 'Demi'),
 ('Hannah Montana – Der Film', 2009, 'Miley Cyrus The Climb', 'Miley'),
 ('Die Monster AG', 2001, "If I Didn't Have You Billy Crystal John Goodman", 'Crystal'),
 ('Ghostbusters', 1984, 'Ray Parker Jr Ghostbusters', 'Parker'),
]
