"""Zusätzliche Kandidaten für „Serien & Filme“ (nur Kinderserien und Filme 1995–2010)."""
ENTRIES = [
 # Kinderserien
 ('Die Powerpuff Girls', 1998, 'Powerpuff Girls theme', ''),
 ('Dexters Labor', 1996, "Dexter's Laboratory theme", ''),
 ('Johnny Bravo', 1997, 'Johnny Bravo theme', ''),
 ('Ed, Edd n Eddy', 1999, 'Ed Edd n Eddy theme', ''),
 ('Hey Arnold!', 1996, 'Hey Arnold theme', ''),
 ('Cosmo & Wanda – Wenn Elfen helfen', 2001, 'Fairly OddParents theme', ''),
 ('Jimmy Neutron', 2002, 'Jimmy Neutron theme', ''),
 ('Danny Phantom', 2004, 'Danny Phantom theme', ''),
 ('Avatar – Der Herr der Elemente', 2005, 'Avatar The Last Airbender main title', ''),
 ('Hotel Zack & Cody', 2005, 'Here I Am Suite Life of Zack and Cody theme', ''),
 ('Sonny Munroe', 2009, 'Demi Lovato So Far So Great', 'Demi Lovato'),
 ('Jonas', 2009, 'Jonas Brothers Live to Party', 'Jonas'),
 ('LazyTown', 2004, 'LazyTown Bing Bang', ''),
 ('Winx Club', 2004, 'Winx Club theme', ''),
 ('Lizzie McGuire', 2001, 'Lizzie McGuire theme Angie Jaree', ''),
 ('Totally Spies', 2001, 'Totally Spies theme song english', ''),
 ('Pinky und der Brain', 1995, 'Pinky and the Brain theme', ''),
 ('Yu-Gi-Oh!', 2000, 'Yu-Gi-Oh theme song', ''),
 ('Naruto', 2002, 'Naruto opening', ''),
 ('Bob der Baumeister', 1998, 'Bob the Builder Can We Fix It', ''),
 ('Die Wilden Kerle', 2003, 'Die Wilden Kerle Bananafishbones', ''),
 # Kinder- & Familienfilme
 ('Space Jam', 1996, 'Quad City DJs Space Jam', 'Quad City'),
 ('Lilo & Stitch', 2002, 'Hawaiian Roller Coaster Ride', ''),
 ('Findet Nemo', 2003, 'Robbie Williams Beyond the Sea', 'Robbie Williams'),
 ('Shrek 2', 2004, 'Counting Crows Accidentally in Love', 'Counting Crows'),
 ('Shrek 2', 2004, 'Holding Out for a Hero Jennifer Saunders', 'Saunders'),
 ('Die Unglaublichen', 2004, 'The Incredits Michael Giacchino', 'Giacchino'),
 ('Madagascar', 2005, 'I Like to Move It Sacha Baron Cohen Madagascar', ''),
 ('Ratatouille', 2007, 'Le Festin Camille', 'Camille'),
 ('Kung Fu Panda', 2008, 'Kung Fu Fighting Cee Lo Green Jack Black', ''),
 ('WALL·E', 2008, 'Peter Gabriel Down to Earth', 'Gabriel'),
 ('Oben', 2009, 'Michael Giacchino Married Life', 'Giacchino'),
 ('Ich – Einfach unverbesserlich', 2010, 'Pharrell Despicable Me', 'Pharrell'),
 ('Toy Story 3', 2010, "Randy Newman We Belong Together Toy Story 3", 'Newman'),
 ('Die Prinzessinnen-Tagebücher', 2001, 'Myra Miracles Happen', 'Myra'),
 ('Popstar auf Umwegen', 2003, 'Hilary Duff What Dreams Are Made Of', 'Duff'),
 ('High School Musical 3', 2008, 'High School Musical 3 Now or Never', ''),
 ('Camp Rock 2', 2010, "Camp Rock 2 Can't Back Down", ''),
 ('Twilight', 2008, 'Paramore Decode', 'Paramore'),
 ('Die Chroniken von Narnia', 2005, 'Narnia The Blitz 1940 Harry Gregson-Williams', 'Gregson'),
 ('Der König der Löwen 2', 1998, 'We Are One Lion King 2', ''),
 # Blockbuster
 ('Titanic', 1997, 'Celine Dion My Heart Will Go On', 'Dion'),
 ('Armageddon', 1998, "Aerosmith I Don't Want to Miss a Thing", 'Aerosmith'),
 ('Mission: Impossible', 1996, 'Adam Clayton Larry Mullen Theme from Mission Impossible', 'Clayton'),
 ('Spider-Man', 2002, 'Danny Elfman Spider-Man Main Title', 'Elfman'),
 ('Gladiator', 2000, 'Hans Zimmer Now We Are Free', 'Zimmer'),
 ('Matrix', 1999, 'Rob Dougan Clubbed to Death', 'Dougan'),
 ('Fluch der Karibik 2', 2006, 'Hans Zimmer Jack Sparrow', 'Zimmer'),
 ('Twilight', 2008, 'Carter Burwell Bella s Lullaby', 'Burwell'),
 ('Der Schuh des Manitu', 2001, 'Der Schuh des Manitu Superstar', ''),
]
